FROM alpine:latest

# Set the working directory
WORKDIR /app

# Copy the text file into the image
COPY message.txt /app/message.txt

# cat the contents of the text file to the terminal
CMD ["cat", "/app/message.txt"]